### ISSUE TITLE
examples/perf/io-perf fails with segmentation fault with io-uring:

### ISSUE THREAD

**Issue by hutm** [alibaba/PhotonLibOS#476]
examples/perf/io-perf fails with segmentation fault with io-uring:
```
(gdb) run
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: io-perf --disk-path /dev/nvme2n1p2 --disk_size 100000000000 --io_uring
2024/05/09 15:54:40.117604|INFO |th=0000000000000000|photon_io_perf.cpp:79|main:Specify disk /dev/nvme2n1p2 size 100000000000
2024/05/09 15:54:40.117801|INFO |th=00007FFFF782A200|iouring-wrapper.cpp:668|new_iouring:Init event engine: iouring [is_master=1]
2024/05/09 15:54:40.117813|INFO |th=00007FFFF782A200|iouring-wrapper.cpp:516|check_register_file_support:iouring: register_files is enabled

Program received signal SIGSEGV, Segmentation fault.
0x0000000000817826 in free ()
(gdb) bt
#0  0x0000000000817826 in free ()
#1  0x0000000000440a54 in photon::iouringEngine::init() ()
#2  0x000000000043f664 in photon::new_iouring(bool) ()
#3  0x00000000004229d5 in photon::init(unsigned long, unsigned long, photon::PhotonOptions const&) ()
#4  0x000000000041c40a in main ()
```

**Comment by beef9999** [comment]
Photon uses liburing 2.3, you can try this cmd to download and build from source

https://photonlibos.github.io/docs/introduction/how-to-build#case-1-staitcally-build-all-third-party-libs
